"""Add icon column to skills table

Revision ID: 45709ca1a055
Revises: 
Create Date: 2026-02-20 23:28:03.527761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45709ca1a055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
